version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '3000:3000'  # Expose port 3000 for the backend
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis:7.4.0
    container_name: redis
    ports:
      - '6379:6379'  # Expose port 6379 for Redis
    networks:
      - app-network

  frontend:
    build:
      context: ./src_fe
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3001:3001'  # Expose port 3001 for the React app (default port is 3000 in the container)
    networks:
      - app-network
    environment:
      - NODE_ENV=development  # Optional: Set environment variable for development

networks:
  app-network:
    driver: bridge